// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6gFzRDQyw6ngcBPFhY1r9BIyg_3FLwQE',
    appId: '1:450885917681:web:945e691569f6488a238250',
    messagingSenderId: '450885917681',
    projectId: 'chat-demo-5024c',
    authDomain: 'chat-demo-5024c.firebaseapp.com',
    databaseURL: 'https://chat-demo-5024c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-demo-5024c.appspot.com',
    measurementId: 'G-Q41JWT8MQS',
  );
/*
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnepnOqw-YngZC_H7zt54Va2_kwT4f1Jk',
    appId: '1:450885917681:android:1f78f5eb7066343f238250',
    messagingSenderId: '450885917681',
    projectId: 'chat-demo-5024c',
    databaseURL: 'https://chat-demo-5024c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-demo-5024c.appspot.com',
  );*/
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMwKKR6r-9eS_N2EUl_x4gg1EkW6ly34',
    appId: '1:697503742825:android:7814077f092ba4245fdbf8',
    messagingSenderId: '697503742825',
    projectId: 'connnectycubesamples',
    storageBucket: 'connnectycubesamples.appspot.com',
  );
  // databaseURL: 'https://chat-demo-5024c-default-rtdb.firebaseio.com',

/*  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmS8IZYleQsYraXJl7Medt5md-vNAbC1I',
    appId: '1:450885917681:ios:609190c4d5efd3c7238250',
    messagingSenderId: '450885917681',
    projectId: 'chat-demo-5024c',
    databaseURL: 'https://chat-demo-5024c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-demo-5024c.appspot.com',
    iosClientId: '450885917681-020i2k2497p8k51tgcmiqhqvt26o74q6.apps.googleusercontent.com',
    iosBundleId: 'com.connectycube.flutter.chatSample.app',
  ); */
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWMwKKR6r-9eS_N2EUl_x4gg1EkW6ly34',
    appId: '1:697503742825:ios:4c8a64727742fb1e5fdbf8',
    messagingSenderId: '697503742825	',
    projectId: 'connnectycubesamples',
    databaseURL: 'https://connnectycubesamples-default-rtdb.firebaseio.com',
    storageBucket: 'connnectycubesamples.appspot.com',
    iosClientId: '697503742825-i3m9hbm7ubjbiua8lpa6tg86k13akr2f.apps.googleusercontent.com',
    iosBundleId: 'com.bv.mainCourt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmS8IZYleQsYraXJl7Medt5md-vNAbC1I',
    appId: '1:450885917681:ios:fe146fe318c74b8c238250',
    messagingSenderId: '450885917681',
    projectId: 'chat-demo-5024c',
    databaseURL: 'https://chat-demo-5024c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-demo-5024c.appspot.com',
    iosClientId: '450885917681-4a6fkopcpkbfr2nf7rftot8dcfduiir7.apps.googleusercontent.com',
    iosBundleId: 'com.connectycube.flutter.chatSample.macOS',
  );
}
